import {describe,it,expect} from 'vitest';
import {evaluateAction,closeAction,actionTimeline,qualificationReminderStatus,createQualificationReminderAction,qualificationDocumentStoragePath,coachQualificationChecklistSummary} from '@mentis/core';
describe('actions engine',()=>{it('breaches at configured time',()=>expect(evaluateAction({id:'a',dueAt:'2026-01-01T00:00:00Z',breachAt:'2026-01-02T00:00:00Z',status:'open'},'2026-01-02T00:00:00Z').status).toBe('breached'));it('closed actions do not reopen',()=>expect(evaluateAction({id:'a',dueAt:'',breachAt:'2020-01-01',status:'closed'},'2026-01-01').status).toBe('closed'));it('creates configurable offsets',()=>expect(actionTimeline('2026-03-01T00:00:00Z',86400000,604800000)).toEqual({dueAt:'2026-02-28T00:00:00.000Z',breachAt:'2026-02-22T00:00:00.000Z'}));it('closes an action',()=>expect(closeAction({id:'a',dueAt:'',status:'open'}).status).toBe('closed'));it('flags qualification expiry before the reminder window',()=>expect(qualificationReminderStatus('2026-02-20T00:00:00.000Z','2026-03-10T00:00:00.000Z',30)).toBe('expiring_soon'));it('creates a coach reminder action for renewal',()=>expect(createQualificationReminderAction({coachStaffId:'staff-1',qualificationTitle:'Safeguarding',expiresAt:'2026-03-10T00:00:00.000Z',reminderDays:30,organizationId:'org-1'})).toEqual({organizationId:'org-1',assigneeId:'staff-1',title:'Renew Safeguarding certificate',dueAt:'2026-02-08T00:00:00.000Z',status:'open'}));it('creates a stable storage path for qualification proof files',()=>expect(qualificationDocumentStoragePath({organizationId:'org-1',staffId:'staff-1',qualificationTypeId:'qual-1',fileName:'dbs.pdf'})).toMatch(/^org-1\/staff-1\/qualifications\/qual-1\//));it('builds a required qualification checklist summary for a coach',()=>expect(coachQualificationChecklistSummary([
  {id:'qual-1',name:'DBS',category:'dbs',is_mandatory:true,requires_document_upload:true,reminder_days:30},
  {id:'qual-2',name:'Safeguarding',category:'safeguarding',is_mandatory:true,requires_document_upload:true,reminder_days:30},
  {id:'qual-3',name:'First aid',category:'first_aid',is_mandatory:false,requires_document_upload:false,reminder_days:30},
],[{qualification_type_id:'qual-1',expires_at:'2026-05-01T00:00:00.000Z',document_url:'https://example.com/dbs.pdf'},{qualification_type_id:'qual-2',expires_at:'2026-02-15T00:00:00.000Z',document_url:''}], '2026-02-01T00:00:00.000Z')).toEqual(expect.arrayContaining([
  expect.objectContaining({qualificationTypeId:'qual-1',required:true,isComplete:true}),
  expect.objectContaining({qualificationTypeId:'qual-2',required:true,isComplete:false,hasDocument:false}),
  expect.objectContaining({qualificationTypeId:'qual-3',required:false,isComplete:false}),
])));});
