import {describe,it,expect} from 'vitest';
import {buildICS,upcomingWindow,anonymiseMember,buildRecordExport,exportToCSV,can,permissionsUnion,switchableRoles,parseCSV,validateMemberRows,attendancePct,memberAnalytics,tasterFunnel,postStandbyEntries,zeroStandby,expectedEnrollments,pauseEnrollment,promoteNextWaitlisted,EMAIL_TEMPLATES,renderTemplate,validateCancellation,isTaskBillable,duplicateInvoice,expiredConsents,rankResults,validateDiaryImport,matchForm,gbp} from '@mentis/core';
describe('round-8 + ops',()=>{
 it('ICS valid & windowed',()=>{const ev=[{uid:'1',title:'A',startsAt:'2026-02-01T10:00:00Z',endsAt:'2026-02-01T11:00:00Z'}];const ics=buildICS('Cal',ev);expect(ics).toContain('BEGIN:VCALENDAR');expect(ics).toContain('END:VCALENDAR');expect(upcomingWindow(ev,8,new Date('2026-01-01T00:00:00Z'))).toHaveLength(1);expect(upcomingWindow(ev,1,new Date('2026-03-01T00:00:00Z'))).toHaveLength(0);});
 it('GDPR export + erasure retains financials',()=>{const m={id:'abcdefgh',name:'Kid',photoRef:'p',specialNeeds:'x',nokName:'n',nokPhone:'p'};const a=anonymiseMember(m);expect(a.name).toContain('Erased');expect(a.photoRef).toBeUndefined();const e=buildRecordExport({profile:{},consents:[],attendance:[],feedbackSummary:[],rankings:[],matches:[],debits:[{amount:1}]});expect(e.debits).toHaveLength(1);expect(exportToCSV('members',[{a:'1'}])).toContain('a');});
 it('permissions: role switcher renders selected role; union is floor',()=>{expect(can('SPARRER','invoices.approve')).toBe(false);expect(can('COACH','invoices.draft')).toBe(true);expect(can('ADMIN','users.manage')).toBe(false);expect(can('SUPER_ADMIN','users.manage')).toBe(true);expect(permissionsUnion(['COACH','SPARRER']).has('attendance.mark')).toBe(true);expect(switchableRoles(['SPARRER','COACH'])).toEqual(['COACH','SPARRER']);});
 it('CSV import with error reporting',()=>{const rows=parseCSV('name,dateOfBirth\nAmy,2015-01-01\n,2016-01-01');const r=validateMemberRows(rows);expect(r.valid).toHaveLength(1);expect(r.errors[0].row).toBe(3);});
 it('reports: attendance, analytics, funnel',()=>{expect(attendancePct([{status:'present'},{status:'absent'}] as any)).toBe(50);const an=memberAnalytics([{opponent:'X',result:'W',date:'2026-01-01'} as any],[{status:'present'}] as any);expect(an.winLoss.wins).toBe(1);expect(an.form).toEqual(['W']);expect(matchForm([])).toEqual([]);expect(tasterFunnel([{status:'requested'},{status:'converted'}])).toEqual({requested:1,tried:1,converted:1});expect(gbp(2500)).toBe('£25.00');});
 it('cancellation posts standby; zero allowed',()=>{const s={id:'s',venueId:'v',start:'2026-01-01T10:00Z',end:'2026-01-01T11:00Z',assignments:[{staffId:'c',capacity:'lead',rateCents:100,start:'',end:''}]} as any;const sb=postStandbyEntries(s,'2026-01-01');expect(sb[0].kind).toBe('standby');expect(zeroStandby(sb[0]).billable).toBe(false);expect(validateCancellation({status:'scheduled'} as any,'')).toContain('cancellation reason is required');});
 it('pause excludes from expected; promotion needs capacity',()=>{const list=expectedEnrollments([{status:'active',expected:true},{status:'paused',expected:false}] as any);expect(list).toHaveLength(1);expect(pauseEnrollment({status:'active',expected:true} as any,'injury').expected).toBe(false);expect(promoteNextWaitlisted([],1,1)).toBeNull();});
 it('task approval separation + one-invoice-per-period',()=>{expect(isTaskBillable({status:'done',approvedAt:'x'} as any)).toBe(true);expect(isTaskBillable({status:'done'} as any)).toBe(false);expect(duplicateInvoice([{staffId:'s',periodStart:'a',periodEnd:'b'}] as any,'s','a','b')).toBe(true);});
 it('consent expiry + RLS-safe search + diary import + templates',()=>{expect(expiredConsents({consents:[{kind:'photo',granted:true,validUntil:'2020-01-01'}]} as any,'2026-01-01')).toEqual(['photo']);expect(rankResults('amy',[{kind:'member',id:'1',title:'Amy'}] as any)[0].title).toBe('Amy');expect(validateDiaryImport([{name:'Open',startsOn:'2026-03-01',endsOn:'2026-03-02',source:'tte'}]).valid).toHaveLength(1);const r=renderTemplate(EMAIL_TEMPLATES.breachAlert,{session:'Tue',when:'x',colour:'RED',action:'y'});expect(r.subject).toContain('Tue');});
});
