-- Mentis foundation: scheduling, staffing and auditable billing
create type session_status as enum ('scheduled','cancelled','postponed','completed');
create type holiday_kind as enum ('term_holiday_week','bank_holiday','manual');
create type time_entry_kind as enum ('planned','actual','standby');
create type invoice_status as enum ('draft','pendingApproval','approved','paid');
create type action_status as enum ('open','breached','closed');

alter table mentis_sessions add column status session_status not null default 'scheduled';
alter table mentis_sessions add column schedule_id uuid;
create table mentis_holiday_calendar (id uuid primary key default gen_random_uuid(), organization_id uuid not null references mentis_organizations(id), name text not null, kind holiday_kind not null, starts_on date not null, ends_on date not null, check(ends_on >= starts_on));
create table mentis_weekly_schedules (id uuid primary key default gen_random_uuid(), organization_id uuid not null references mentis_organizations(id), venue_id uuid not null references mentis_venues(id), name text not null, day_of_week smallint not null check(day_of_week between 0 and 6), valid_from date not null, valid_to date not null, start_time time not null, end_time time not null, check(valid_to >= valid_from), check(end_time > start_time));
create table mentis_rate_cards (id uuid primary key default gen_random_uuid(), organization_id uuid not null references mentis_organizations(id), staff_id uuid not null references mentis_staff(id), label text not null, rate_cents integer not null check(rate_cents >= 0), valid_from date not null);
create table mentis_schedule_staff (schedule_id uuid not null references mentis_weekly_schedules(id) on delete cascade, staff_id uuid not null references mentis_staff(id), capacity text not null check(capacity in ('lead','assistant','sparrer')), rate_card_id uuid not null references mentis_rate_cards(id), primary key(schedule_id,staff_id,capacity));
create table mentis_schedule_overrides (id uuid primary key default gen_random_uuid(), organization_id uuid not null references mentis_organizations(id), schedule_id uuid references mentis_weekly_schedules(id), session_id uuid references mentis_sessions(id), starts_at timestamptz not null, ends_at timestamptz not null, venue_id uuid references mentis_venues(id), original_values jsonb not null default '{}', override_values jsonb not null, created_by uuid not null, created_at timestamptz not null default now(), check(ends_at > starts_at), check(schedule_id is not null or session_id is not null));
create table mentis_session_staffing (id uuid primary key default gen_random_uuid(), session_id uuid not null references mentis_sessions(id) on delete cascade, staff_id uuid not null references mentis_staff(id), capacity text not null check(capacity in ('lead','assistant','sparrer')), rate_card_id uuid not null references mentis_rate_cards(id), planned_start timestamptz not null, planned_end timestamptz not null, unique(session_id,staff_id,capacity), check(planned_end > planned_start));
create table mentis_staff_availability (id uuid primary key default gen_random_uuid(), organization_id uuid not null references mentis_organizations(id), staff_id uuid not null references mentis_staff(id), starts_at timestamptz not null, ends_at timestamptz not null, available boolean not null, reason text, recorded_by uuid not null, recorded_at timestamptz not null default now(), check(ends_at > starts_at));
create table mentis_tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references mentis_organizations(id), title text not null, task_type text not null, assignee_id uuid references mentis_staff(id), amount_cents integer check(amount_cents >= 0), approved_at timestamptz, approved_by uuid, work_hours numeric(8,2), due_at timestamptz);
create table mentis_staff_time_entries (id uuid primary key default gen_random_uuid(), organization_id uuid not null references mentis_organizations(id), staff_id uuid not null references mentis_staff(id), session_id uuid references mentis_sessions(id), task_id uuid references mentis_tasks(id), kind time_entry_kind not null, starts_at timestamptz not null, ends_at timestamptz not null, hours numeric(8,2) generated always as (extract(epoch from (ends_at-starts_at))/3600) stored, rate_cents integer not null check(rate_cents >= 0), bill_state text not null default 'unbilled' check(bill_state in ('unbilled','billed')), pending_review boolean not null default false, created_at timestamptz not null default now(), check(ends_at > starts_at), check((session_id is not null) <> (task_id is not null)));
create table mentis_invoices (id uuid primary key default gen_random_uuid(), organization_id uuid not null references mentis_organizations(id), staff_id uuid not null references mentis_staff(id), period_start timestamptz not null, period_end timestamptz not null, status invoice_status not null default 'draft', created_by uuid not null, approved_by uuid, approved_at timestamptz, paid_at timestamptz, payment_reference text, unique(staff_id,period_start,period_end), check(period_end > period_start));
create table mentis_invoice_lines (id uuid primary key default gen_random_uuid(), invoice_id uuid not null references mentis_invoices(id) on delete cascade, time_entry_id uuid unique references mentis_staff_time_entries(id), task_id uuid references mentis_tasks(id), hours numeric(8,2) not null, rate_cents integer not null, amount_cents integer generated always as (round(hours * rate_cents)) stored, check((time_entry_id is not null) <> (task_id is not null)));
create table mentis_action_types (id uuid primary key default gen_random_uuid(), organization_id uuid not null references mentis_organizations(id), name text not null, trigger text not null check(trigger in ('event','activity','manual')), due_offset interval, breach_offset interval, unique(organization_id,name));
create table mentis_pending_actions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references mentis_organizations(id), action_type_id uuid not null references mentis_action_types(id), title text not null, assignee_id uuid references mentis_staff(id), linked_entity_type text, linked_entity_id uuid, due_at timestamptz not null, breach_at timestamptz, status action_status not null default 'open');

create index sessions_schedule_idx on mentis_sessions(schedule_id); create index time_entries_staff_date_idx on mentis_staff_time_entries(staff_id,starts_at); create index actions_queue_idx on mentis_pending_actions(organization_id,status,due_at);

-- Prevent changing or deleting approved mentis_invoices and their lines.
create or replace function prevent_locked_invoice_change() returns trigger language plpgsql as $$
begin if exists(select 1 from mentis_invoices where id=case when TG_TABLE_NAME = 'mentis_invoice_lines' then old.invoice_id else old.id end and status in ('approved','paid')) then raise exception 'approved invoice is locked'; end if; if TG_OP = 'DELETE' then return old; else return new; end if; end $$;
create trigger invoice_lock before update or delete on mentis_invoices for each row execute function prevent_locked_invoice_change();
create trigger invoice_line_lock before update or delete on mentis_invoice_lines for each row execute function prevent_locked_invoice_change();

-- Organization-scoped RLS helper policies. The base migration's role helper remains the security floor.
do $$ declare t text; begin foreach t in array array['mentis_holiday_calendar','mentis_weekly_schedules','mentis_rate_cards','mentis_schedule_staff','mentis_schedule_overrides','mentis_session_staffing','mentis_staff_availability','mentis_tasks','mentis_staff_time_entries','mentis_invoices','mentis_invoice_lines','mentis_action_types','mentis_pending_actions'] loop execute format('alter table %I enable row level security',t); end loop; end $$;
create policy holiday_access on mentis_holiday_calendar for all using (organization_id in (select organization_id from mentis_staff where user_id=auth.uid()));
create policy schedule_access on mentis_weekly_schedules for all using (organization_id in (select organization_id from mentis_staff where user_id=auth.uid()));
create policy rate_access on mentis_rate_cards for all using (has_mentis_role(organization_id,'SUPER_ADMIN') or has_mentis_role(organization_id,'ADMIN'));
create policy schedule_staff_access on mentis_schedule_staff for all using (schedule_id in (select id from mentis_weekly_schedules where organization_id in (select organization_id from mentis_staff where user_id=auth.uid())));
create policy override_access on mentis_schedule_overrides for all using (organization_id in (select organization_id from mentis_staff where user_id=auth.uid()));
create policy staffing_access on mentis_session_staffing for all using (session_id in (select id from mentis_sessions where organization_id in (select organization_id from mentis_staff where user_id=auth.uid())));
create policy availability_access on mentis_staff_availability for all using (organization_id in (select organization_id from mentis_staff where user_id=auth.uid()));
create policy task_access on mentis_tasks for all using (organization_id in (select organization_id from mentis_staff where user_id=auth.uid()));
create policy time_entry_access on mentis_staff_time_entries for all using (organization_id in (select organization_id from mentis_staff where user_id=auth.uid()));
create policy invoice_access on mentis_invoices for all using (organization_id in (select organization_id from mentis_staff where user_id=auth.uid()));
create policy invoice_line_access on mentis_invoice_lines for all using (invoice_id in (select id from mentis_invoices where organization_id in (select organization_id from mentis_staff where user_id=auth.uid())));
create policy action_type_access on mentis_action_types for all using (organization_id in (select organization_id from mentis_staff where user_id=auth.uid()));
create policy action_access on mentis_pending_actions for all using (organization_id in (select organization_id from mentis_staff where user_id=auth.uid()));
